### ISSUE TITLE
Code mistake (5.6.2)

### ISSUE THREAD

**Issue by kosgdk** [underscoreio/essential-scala#27]
**5.6.2 Function Types**

```
class  Box[A](value: A) {
     /** Apply `func` to `value`, returning a `Box` of the result. */
     def map[B](func: Function1[A, B]): Box[B] =
          Box(func(a)) // Mistake here
}
```
`Box(func(a))` invalid parameter `a`, should be `Box(func(value))`

Also, there is no method `apply` in `Box` class, so `Box(func(value))` will not compile until `apply` method will be implented or `Box` will be a `case` class.

**Comment by davegurnell** [comment]
Looks like @daniashers fixed this in the Tut port.
