### ISSUE TITLE
Code mistake (6.1.4)

### ISSUE THREAD

**Issue by kosgdk** [underscoreio/essential-scala#28]
**6.1.4 Sorting elements**

```
sequence.sortWith(_ < _)
// res: Seq[Int] = List(3, 2, 1)
```
The result will be `List(1, 2, 3)`, but considering that initial sequence is `List(1, 2, 3)` too, it's better to fix sort function to `_ > _`

**Comment by davegurnell** [comment]
Good point. Agreed!
