### ISSUE TITLE
Code typo (6.2.7.2)

### ISSUE THREAD

**Issue by kosgdk** [underscoreio/essential-scala#35]
**6.2.7.2 Do-It-Yourself**

Some duplicated strings in code:

```
var mutable = 1
var mutable = 1 //Duplicate
mutable: Int = 1

mutable = 2
mutable = 2 //Duplicate
mutable: Int = 2
```

**Comment by davegurnell** [comment]
Looks like @daniashers fixed these when she moved our code to Tut. Thanks for the spot though!
