### ISSUE TITLE
Missing spaces (6.4)

### ISSUE THREAD

**Issue by kosgdk** [underscoreio/essential-scala#36]
**6.4 Options**

Missing spaces near dash:
> We have seen Options in passing a number of times **already—they** represent values that

**Comment by davegurnell** [comment]
Apparently the kind of dash we're using here is an "em dash". According to the grammar gods, it is conventionally written without spaces. See the bottom of this article:

http://www.thepunctuationguide.com/em-dash.html

For what it's worth, I used to write these dashes with spaces until @d6y showed me this guide. We now leave the spaces out throughout our books. Em dashes are written as triple hyphens in Markdown---hopefully we're consistent in our treatment of them.
