### ISSUE TITLE
Code color (6.8.1)

### ISSUE THREAD

**Issue by kosgdk** [underscoreio/essential-scala#39]
**6.8.1 Maps**

![image](https://user-images.githubusercontent.com/16893004/27794729-05de0bc0-600c-11e7-9ee9-0202e1314afd.png)

`Map(a -> 1, b -> 2, c -> 3)` should be the same color as commented line above

This issue occurs throughout the book.

**Comment by davegurnell** [comment]
This seems to have been fixed since we moved to A5.
