### ISSUE TITLE
Code mistake (C.5.40)

### ISSUE THREAD

**Issue by kosgdk** [underscoreio/essential-scala#40]
**C.5.40 Solution to: Union of Maps**

```scala
def union[A](map1: Map[A, Int], map2: Map[A, Int]): Map[A, Int] = {
   map1.foldLeft(map2){(map, elt) =>
      val (k, v) = elt
      val newV = map.getOrElse(k, v) //Mistake
      map + (k -> newV)
   }
}
```
This code returns `Map(a -> 2, b -> 4)` instead of desired `Map(a -> 3, b -> 6)`

`val newV = v + map.getOrElse(k, 0)` - that will fix the problem

**Comment by floating-cat** [comment]
This issue has been fixed in https://github.com/underscoreio/essential-scala/commit/c38e3680f75789808d07aaa1d595dfe8fc4cdace.

**Comment by davegurnell** [comment]
Yes -- @daniashers fixed this when she migrated everything to Tut. Thanks all!
