### ISSUE TITLE
Duplicate line (B.6.2.1)

### ISSUE THREAD

**Issue by kosgdk** [underscoreio/essential-scala#50]
### B.6.2.1 Using Mutable Collections Safely

```scala
import scala.collection.mutable
import scala.collection.mutable // Duplicaate line

mutable.Seq(1, 2, 3)
// res: scala.collection.mutable.Seq[Int] = ArrayBuffer(1, 2, 3)

Seq(1, 2, 3)
// res: Seq[Int] = List(1, 2, 3)
```

**Comment by floating-cat** [comment]
This issue has been fixed in https://github.com/underscoreio/essential-scala/commit/bfe9cd949138f0c18bd0aa3ceffe362db61d5f16#diff-08b2e17a985cfa7e8c831d133eb51b41L56.

**Comment by davegurnell** [comment]
Thanks for the feedback!
