### ISSUE TITLE
An example in `options-as-sequences` is not clearly explained

### ISSUE THREAD

**Issue by xieyuheng** [underscoreio/essential-scala#77]
In https://github.com/underscoreio/essential-scala/blob/develop/src/pages/collections/options.md#options-as-sequences
This example is not clearly explained:

``` scala
def readInt(str: String): Option[Int] =
  if(str matches "-?\\d+") Some(str.toInt) else None

Seq(readInt("1"), readInt("b"), readInt("3")).flatMap(x => x)
// res1: Seq[Int] = List(1, 3)
```

Implicit conversion from `Some` to `scala.collection.GenTraversableOnce` requires more explanation.

**Comment by davegurnell** [comment]
Fair point. We'll take a look!
